version: '3'

services:
  app:
    build: .docker/images/app
    image: laravel-app:1.0
    depends_on:
      - mysql
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql:cached

  nginx:
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - .docker/config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - app

  node:
    image: node:14.16-alpine3.10
    working_dir: /usr/src/app
    volumes:
      - $PWD:/usr/src/app
    command: "npm install"
    command: "npm run dev"

  composer:
    image: composer:1.10
    working_dir: /app
    volumes:
      - $PWD:/app
    command: "composer install"

volumes: 
  mysql-data:
    name: "fitAdmin-mysql-data"
    driver: local