version: '3'

services:
  app:
    build: .docker/images/app
    image: laravel-app:1.0
    restart: always
    depends_on:
      - mysql
    volumes:
      - ${APPLICATION_DIR}:/application:cached

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - ${DB_DOCKER_HOST}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql:cached

  nginx:
    image: nginx:1.19
    restart: always
    ports:
      - ${WEB_HOST}:80
    volumes:
      - .docker/config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ${APPLICATION_DIR}:/application:cached
    depends_on:
      - app

  node:
    image: node:14.16-alpine3.10
    depends_on: 
      - app
    working_dir: /usr/src/app
    volumes:
      - ${APPLICATION_DIR}:/usr/src/app
    command: "npm install"

  composer:
    image: composer:1.10
    depends_on: 
      - app
    working_dir: /app
    volumes:
      - ${APPLICATION_DIR}:/app
    command: "composer install"

volumes: 
  mysql-data:
    name: "fitAdmin-mysql-data"
    driver: local