version: '3'

services:
  app:
    build: .docker/images/app
    image: laravel-app
    depends_on:
      - mysql
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql:cached

  nginx:
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - .docker/config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - app

volumes: 
  mysql-data:
    name: "fitAdmin-mysql-data"
    driver: local